    # def handle_alert(self, message_header, message):
    #     print("An alert was received!")
    #     print("version:", message.alert_info.version)
    #     print("relay_until:", message.alert_info.relay_until)
    #     print("expiration:", message.alert_info.expiration)
    #     print("id:", message.alert_info.id)
    #     print("cancel:", message.alert_info.cancel)
    #     print("set_cancel:", message.alert_info.set_cancel)
    #     print("min_ver:", message.alert_info.min_ver)
    #     print("max_ver:", message.alert_info.max_ver)
    #     print("set_sub_ver:", message.alert_info.set_sub_ver)
    #     print("priority:", message.alert_info.priority)
    #     print("comment:", message.alert_info.comment)
    #     print("status_bar", message.alert_info.status_bar)
    #     print("reserved", message.alert_info.reserved)
    #     # print("payload", message.payload)
    #     print("signature", message.signature)
    #     print("===================")
